/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;


import controlador.ProcesosBD;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import modelo.Usuario;

/**
 *
 * @author alvaro
 */
public class Registro extends javax.swing.JPanel {

    /**
     * Creates new form Registro
     */
    public Registro() {
        initComponents();
        
        
    }
  public void mostrarRegistro() {
        this.setVisible(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        fieldUsuario = new javax.swing.JTextField();
        FieldPassConfirm = new javax.swing.JTextField();
        FieldPass = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cancelar = new javax.swing.JButton();
        BotonAgregarNuevoUsuario = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        jMenu3.setText("jMenu3");

        jMenu4.setText("jMenu4");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fieldUsuario.setBackground(new java.awt.Color(255, 255, 204));
        fieldUsuario.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(fieldUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 164, -1));

        FieldPassConfirm.setBackground(new java.awt.Color(255, 255, 204));
        FieldPassConfirm.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(FieldPassConfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 164, -1));

        FieldPass.setBackground(new java.awt.Color(255, 255, 204));
        FieldPass.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(FieldPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 164, -1));

        jLabel2.setFont(new java.awt.Font("Malgun Gothic", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Repita su contraseña:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, -1, -1));

        jLabel1.setFont(new java.awt.Font("Malgun Gothic", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Ingrese su contraseña:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, -1, -1));

        jLabel3.setFont(new java.awt.Font("Malgun Gothic", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Ingrese su nuevo usuario:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 190, 20));

        cancelar.setBackground(new java.awt.Color(255, 255, 204));
        cancelar.setFont(new java.awt.Font("Malgun Gothic", 1, 12)); // NOI18N
        cancelar.setForeground(new java.awt.Color(0, 0, 0));
        cancelar.setText("Cancelar");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });
        jPanel1.add(cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, -1, -1));

        BotonAgregarNuevoUsuario.setBackground(new java.awt.Color(255, 255, 204));
        BotonAgregarNuevoUsuario.setFont(new java.awt.Font("Malgun Gothic", 1, 12)); // NOI18N
        BotonAgregarNuevoUsuario.setForeground(new java.awt.Color(0, 0, 0));
        BotonAgregarNuevoUsuario.setText("Agregar");
        BotonAgregarNuevoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAgregarNuevoUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(BotonAgregarNuevoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Fondo 400.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BotonAgregarNuevoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAgregarNuevoUsuarioActionPerformed
        String usuario = fieldUsuario.getText();
        String contraseña = FieldPass.getText();
        String confirmacionContraseña = FieldPassConfirm.getText();

        if (usuario.isEmpty() || contraseña.isEmpty() || confirmacionContraseña.isEmpty()) {

            JOptionPane.showMessageDialog(this, "Error: Todos los campos deben ser completados.", "Error", JOptionPane.ERROR_MESSAGE);

            return;
        }

        if (!contraseña.equals(confirmacionContraseña)) {

            JOptionPane.showMessageDialog(this, "Error: Las contraseñas no coinciden.", "Error", JOptionPane.ERROR_MESSAGE);

            return;
        }

        Usuario nuevoUsuario = new Usuario(usuario, contraseña);

        ProcesosBD procesosBD = new ProcesosBD();
        boolean usuarioAgregado = procesosBD.agregarUsuario(nuevoUsuario, confirmacionContraseña);

        if (usuarioAgregado) {
            fieldUsuario.setText("");
            FieldPass.setText("");
            FieldPassConfirm.setText("");

            RegistroExitoso registroExitoso = new RegistroExitoso();
            registroExitoso.setVisible(true);
             SwingUtilities.getWindowAncestor(this).dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Error al agregar el usuario. Inténtelo de nuevo.", "Error", JOptionPane.ERROR_MESSAGE);

        }

    }//GEN-LAST:event_BotonAgregarNuevoUsuarioActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
       SwingUtilities.getWindowAncestor(this).dispose();
       
    }//GEN-LAST:event_cancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAgregarNuevoUsuario;
    private javax.swing.JTextField FieldPass;
    private javax.swing.JTextField FieldPassConfirm;
    private javax.swing.JButton cancelar;
    private javax.swing.JTextField fieldUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
